name: "First Workflow"
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - run: npm install
      - run: npm build
      - run: npm run test
      - uses: ./.github/actions/first_action
        with:
          amazing-creature: mosquito 
        id: debug
      - run: echo There was an amazing message - ${{ steps.debug.outputs.amazing-message }}
