name: Issue
on:
  issues:
    types: [opened]
jobs:
  callIssueAction:
    name: CallIssueAction
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Calling my custom action that uses octokit
        uses: ./.github/actions/issue_action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
